# helpful Links:
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# https://www.youtube.com/watch?v=7I6tHw68DMQ

stages:
  - test
  - benchmark-test

test:
  image: $CI_REGISTRY_IMAGE
  stage: test
  tags:
    - envinf2
  variables:
    R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib/"
    RETICULATE_MINICONDA_PATH: "/root/.local/share/r-miniconda/" #default path
    RETICULATE_PYTHON_ENV: "/root/.local/share/r-miniconda/envs/r-reticulate/"
    # RETICULATE_PYTHON: "$CI_PROJECT_DIR/ci/r-miniconda/envs/r-reticulate/bin/python3"
  script:
    - if [ ! -d "$R_LIBS_USER" ]; then mkdir -p "$R_LIBS_USER"; fi
    - R -e 'withr::with_libpaths(new = Sys.getenv("R_LIBS_USER"), devtools::install_deps(dependencies = T))'
    # checks if the packages from the Imports, Suggests, LinkinTo field
    # are already installed in the cache
    - R -e '.libPaths(new = Sys.getenv("R_LIBS_USER"))'
    # Build and Check r2ogs6
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-build-vignettes --no-manual
    #echo First Stage!
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    untracked: true
    paths:
      - "$R_LIBS_USER"
      - "$RETICULATE_MINICONDA_PATH"
      - "$RETICULATE_PYTHON_ENV"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"'

benchmark-test:
  image: $CI_REGISTRY_IMAGE
  stage: benchmark-test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
  script:
    - R -e 'print("HELLO R")'
    - singularity --version

